Projeto2_NIF_Web/Models/ErrorViewModel.cs
namespace Projeto2_NIF_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projeto2_NIF_Web/Models/NIFDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Projeto2_NIF_Web.Models
{
    public class NIFDbContext : DbContext
    {
        public NIFDbContext(DbContextOptions<NIFDbContext> options) : base(options)
        {

        }
        public DbSet<NIF_Empresa> NIF_Empresa { get; set; }
    }
}

Projeto2_NIF_Web/Models/NIF_Empresa.cs
using System.ComponentModel.DataAnnotations;

namespace Projeto2_NIF_Web.Models
{
    public class NIF_Empresa
    {
        [Key]
        public int NIF { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int PC4 { get; set; }
        public int PC3 { get; set; }
        public string Region { get; set; }
        public string County { get; set; }
        public string Parish { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string Website { get; set; }
        public int Fax { get; set; }
        public string Imagem_URL { get; set; }
    }
}

Projeto2_NIF_Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto2_NIF_Web.Models;
using System.Diagnostics;

namespace Projeto2_NIF_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projeto2_NIF_Web/Controllers/NIF_EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projeto2_NIF_Web.Models;

namespace Projeto2_NIF_Web.Controllers
{
    public class NIF_EmpresaController : Controller
    {
        private readonly NIFDbContext _context;

        public NIF_EmpresaController(NIFDbContext context)
        {
            _context = context;
        }

        // GET: NIF_Empresa
        public async Task<IActionResult> Index()
        {
              return _context.NIF_Empresa != null ? 
                          View(await _context.NIF_Empresa.ToListAsync()) :
                          Problem("Entity set 'NIFDbContext.NIF_Empresa'  is null.");
        }

        // GET: NIF_Empresa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.NIF_Empresa == null)
            {
                return NotFound();
            }

            var nIF_Empresa = await _context.NIF_Empresa
                .FirstOrDefaultAsync(m => m.NIF == id);
            if (nIF_Empresa == null)
            {
                return NotFound();
            }

            return View(nIF_Empresa);
        }

        // GET: NIF_Empresa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NIF_Empresa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NIF,Name,Address,PC4,PC3,Region,County,Parish,Email,Phone,Website,Fax,Imagem_URL")] NIF_Empresa nIF_Empresa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nIF_Empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nIF_Empresa);
        }

        // GET: NIF_Empresa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NIF_Empresa == null)
            {
                return NotFound();
            }

            var nIF_Empresa = await _context.NIF_Empresa.FindAsync(id);
            if (nIF_Empresa == null)
            {
                return NotFound();
            }
            return View(nIF_Empresa);
        }

        // POST: NIF_Empresa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NIF,Name,Address,PC4,PC3,Region,County,Parish,Email,Phone,Website,Fax,Imagem_URL")] NIF_Empresa nIF_Empresa)
        {
            if (id != nIF_Empresa.NIF)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nIF_Empresa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NIF_EmpresaExists(nIF_Empresa.NIF))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nIF_Empresa);
        }

        // GET: NIF_Empresa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.NIF_Empresa == null)
            {
                return NotFound();
            }

            var nIF_Empresa = await _context.NIF_Empresa
                .FirstOrDefaultAsync(m => m.NIF == id);
            if (nIF_Empresa == null)
            {
                return NotFound();
            }

            return View(nIF_Empresa);
        }

        // POST: NIF_Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.NIF_Empresa == null)
            {
                return Problem("Entity set 'NIFDbContext.NIF_Empresa'  is null.");
            }
            var nIF_Empresa = await _context.NIF_Empresa.FindAsync(id);
            if (nIF_Empresa != null)
            {
                _context.NIF_Empresa.Remove(nIF_Empresa);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NIF_EmpresaExists(int id)
        {
          return (_context.NIF_Empresa?.Any(e => e.NIF == id)).GetValueOrDefault();
        }
    }
}

Projeto2_NIF_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Projeto2_NIF_Web/Views/NIF_Empresa/Create.cshtml
@model Projeto2_NIF_Web.Models.NIF_Empresa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NIF_Empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PC4" class="control-label"></label>
                <input asp-for="PC4" class="form-control" />
                <span asp-validation-for="PC4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PC3" class="control-label"></label>
                <input asp-for="PC3" class="form-control" />
                <span asp-validation-for="PC3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parish" class="control-label"></label>
                <input asp-for="Parish" class="form-control" />
                <span asp-validation-for="Parish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem_URL" class="control-label"></label>
                <input asp-for="Imagem_URL" class="form-control" />
                <span asp-validation-for="Imagem_URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto2_NIF_Web/Views/NIF_Empresa/Delete.cshtml
@model Projeto2_NIF_Web.Models.NIF_Empresa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NIF_Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PC4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PC4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PC3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PC3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem_URL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem_URL)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NIF" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Projeto2_NIF_Web/Views/NIF_Empresa/Details.cshtml
@model Projeto2_NIF_Web.Models.NIF_Empresa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NIF_Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PC4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PC4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PC3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PC3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Parish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Parish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Website)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Website)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem_URL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem_URL)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.NIF">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Projeto2_NIF_Web/Views/NIF_Empresa/Edit.cshtml
@model Projeto2_NIF_Web.Models.NIF_Empresa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NIF_Empresa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NIF" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PC4" class="control-label"></label>
                <input asp-for="PC4" class="form-control" />
                <span asp-validation-for="PC4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PC3" class="control-label"></label>
                <input asp-for="PC3" class="form-control" />
                <span asp-validation-for="PC3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Parish" class="control-label"></label>
                <input asp-for="Parish" class="form-control" />
                <span asp-validation-for="Parish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fax" class="control-label"></label>
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem_URL" class="control-label"></label>
                <input asp-for="Imagem_URL" class="form-control" />
                <span asp-validation-for="Imagem_URL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto2_NIF_Web/Views/NIF_Empresa/Index.cshtml
@model IEnumerable<Projeto2_NIF_Web.Models.NIF_Empresa>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" id="NIF">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PC4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PC3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.County)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Parish)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Website)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagem_URL)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PC4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PC3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.County)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parish)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Website)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagem_URL)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NIF">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.NIF">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.NIF">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Projeto2_NIF_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto2_NIF_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto2_NIF_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="http://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto2_NIF_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NIF_Empresa" asp-action="Index">Empresas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Projeto2_NIF_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="http://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>